name: Build ArenaOS
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc make bison flex xorriso mtools nasm

    - name: Download Limine
      run: |
        git clone https://github.com/limine-bootloader/limine.git --branch=v8.x-binary --depth=1
        make -C limine

    - name: Build Kernel
      run: make kernel.elf

    - name: Create ISO
      run: |
        mkdir -p iso_root
        
        # Копируем только ядро и бинарники загрузчика в корень
        cp kernel.elf iso_root/
        cp limine/limine-bios.sys limine/limine-bios-cd.bin limine/limine-uefi-cd.bin iso_root/
        
        # Создаем пустой limine.conf на случай если загрузчик его очень хочет
        echo "TIMEOUT=0" > iso_root/limine.conf
        echo ":ArenaOS" >> iso_root/limine.conf
        echo "PROTOCOL=limine" >> iso_root/limine.conf
        echo "KERNEL_PATH=boot:///kernel.elf" >> iso_root/limine.conf

        # Сборка ISO (Flat mode)
        xorriso -as mkisofs -b limine-bios-cd.bin \
                -no-emul-boot -boot-load-size 4 -boot-info-table \
                --efi-boot limine-uefi-cd.bin \
                -efi-boot-part --efi-boot-image --protective-msdos-label \
                iso_root -o ArenaOS-Reality.iso
                
        ./limine/limine bios-install ArenaOS-Reality.iso

    - name: Upload ISO
      uses: actions/upload-artifact@v4
      with:
        name: ArenaOS-Reality-ISO
        path: ArenaOS-Reality.iso
