name: Build ArenaOS
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Tools
      run: sudo apt-get update && sudo apt-get install -y gcc make xorriso mtools

    - name: Download Limine
      run: |
        git clone https://github.com/limine-bootloader/limine.git --branch=v8.x-binary --depth=1
        make -C limine

    - name: Build Kernel
      run: make kernel.elf

    - name: Create ISO (Byte-Perfect)
      run: |
        mkdir -p iso_root
        
        # СОЗДАЕМ ИДЕАЛЬНЫЙ КОНФИГ БЕЗ СИМВОЛОВ WINDOWS
        # \n - это жесткий перенос строки Linux
        printf "TIMEOUT=3\n:ArenaOS\nPROTOCOL=limine\nKERNEL_PATH=boot:///kernel.elf\n" > iso_root/limine.conf
        
        cp kernel.elf iso_root/
        cp limine/limine-bios.sys limine/limine-bios-cd.bin limine/limine-uefi-cd.bin iso_root/
        
        xorriso -as mkisofs -b limine-bios-cd.bin \
                -no-emul-boot -boot-load-size 4 -boot-info-table \
                --efi-boot limine-uefi-cd.bin \
                -efi-boot-part --efi-boot-image --protective-msdos-label \
                iso_root -o ArenaOS.iso
        
        ./limine/limine bios-install ArenaOS.iso

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: ArenaOS-ISO
        path: ArenaOS.iso
